name: build_and_publish_image

on:
  push:
    branches:
      - master

jobs:
  build_and_publish_image:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: isdb-scanner
      RECISDB_RS_VERSION: 1.2.3
      ISDB_SCANNER_VERSION: 1.3.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.ISDB_SCANNER_VERSION }}-${{ env.RECISDB_RS_VERSION }}
         build-args: |
           RECISDB_RS_VERSION=${{ env.RECISDB_RS_VERSION }}
           ISDB_SCANNER_VERSION=${{ env.ISDB_SCANNER_VERSION }}
